# Deployment da aplicação FakeShop
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
  labels:
    app: fakeshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: fakeshop
        image: tecnicocefet/fakeshop:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "index.py"
        - name: FLASK_ENV
          value: "production"
        - name: DB_HOST
          value: postgre
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: fakeshop
        - name: DB_PASSWORD
          value: Pg1234
        - name: DB_NAME
          value: fakeshop
        - name: DATABASE_URL
          value: "postgresql+psycopg://fakeshop:Pg1234@postgre:5432/fakeshop?sslmode=disable"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 90
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
---
# Deployment do banco de dados PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
  labels:
    app: postgre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:13.16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: fakeshop
        - name: POSTGRES_PASSWORD
          value: Pg1234
        - name: POSTGRES_DB
          value: fakeshop
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
# PersistentVolumeClaim (PVC) para o PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi