# Deployment da aplicação FakeShop
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
  labels:
    app: fakeshop
spec:
  replicas: 2  # Número de réplicas
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: fakeshop
        image: tecnicocefet/fakeshop:latest  # Imagem da aplicação
        ports:
        - containerPort: 5000  # Porta utilizada pela aplicação
        env:
        - name: DB_HOST
          value: postgre  # Nome do serviço do PostgreSQL
        - name: DB_PORT
          value: "5432"  # Porta do banco de dados
        - name: DB_USER
          value: fakeshop  # Usuário do banco de dados
        - name: DB_PASSWORD
          value: Pg1234  # Senha do banco de dados
        - name: DB_NAME
          value: fakeshop  # Nome do banco de dados
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 20  # Tempo maior para inicialização
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30  # Verificação de vida
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---

# Deployment do banco de dados PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
  labels:
    app: postgre
spec:
  replicas: 1  # Réplica única para o banco
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:13.16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: fakeshop  # Usuário do banco de dados
        - name: POSTGRES_PASSWORD
          value: Pg1234  # Senha do banco de dados
        - name: POSTGRES_DB
          value: fakeshop  # Nome do banco de dados
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 10
