# Deployment da aplicação web (FakeShop)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
  labels:
    app: fakeshop
spec:
  replicas: 2  # Número de réplicas
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: fakeshop
        image: tecnicocefet/fakeshop:latest  # Imagem da aplicação
        ports:
        - containerPort: 5000  # Porta usada pela aplicação
        env:
        - name: DB_HOST
          value: postgre
        - name: DB_USER
          value: fakeshop
        - name: DB_PASSWORD
          value: Pg1234
        - name: DB_NAME
          value: fakeshop
        - name: FLASK_APP
          value: index.py
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5

---

# Deployment do banco de dados PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
  labels:
    app: postgre
spec:
  replicas: 1  # Apenas uma réplica para o banco de dados
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:13.16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: fakeshop
        - name: POSTGRES_PASSWORD
          value: Pg1234
        - name: POSTGRES_DB
          value: fakeshop
