name: CI/CD Pipeline for Fake Shop

on:
  push:
    branches:
      - main  # Ou o nome da sua branch principal

jobs:
  # Job CI - Build e Push da imagem Docker
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Verify Dockerfile
        run: ls -l ./src/Dockerfile

      - name: Build and push Docker image
        run: |
          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/fake-shop:${GITHUB_SHA}"
          docker build -t $IMAGE_TAG ./src
          docker tag $IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/fake-shop:latest
          docker push $IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/fake-shop:latest

  # Job CD - Deploy no Kubernetes
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.24.0'

      - name: Set up kubeconfig using token and certificate
        run: |
          # Salva o certificado da CA em um arquivo
          echo "${{ secrets.DO_K8S_CA }}" | base64 -d > ca.crt
          
          # Configura o kubeconfig com o servidor, certificado e token
          kubectl config set-cluster do-nyc1-k8s-devops \
            --server=https://41129ac3-4d1c-458c-9752-c81dd268c049.k8s.ondigitalocean.com \
            --certificate-authority=ca.crt
          
          kubectl config set-credentials do-nyc1-k8s-devops-admin --token=${{ secrets.DO_TOKEN }}
          
          kubectl config set-context do-nyc1-k8s-devops \
            --cluster=do-nyc1-k8s-devops \
            --user=do-nyc1-k8s-devops-admin
          
          kubectl config use-context do-nyc1-k8s-devops

      - name: Check Kubernetes cluster
        run: |
          kubectl get nodes

      - name: Verify Kubernetes context
        run: kubectl config current-context

      - name: Replace image tag in manifests dynamically
        run: |
          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/fake-shop:${GITHUB_SHA}"
          sed -i "s|image:.*|image: $IMAGE_TAG|g" Kubernetes/deployment.yaml

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f Kubernetes/deployment.yaml
          kubectl apply -f Kubernetes/service.yaml

      - name: Wait for Deployment rollout
        run: |
          kubectl rollout status deployment/fake-shop-deployment

      - name: Verify deployment pods
        run: |
          kubectl get pods -l app=fake-shop -o wide

      - name: Show logs from first pod
        run: |
          POD_NAME=$(kubectl get pods -l app=fake-shop -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $POD_NAME
